[package]
name = "caplike"
version = "0.1.0"
edition = "2021"
description = "A CLI tool to perform capistrano-like symlink installations."

[dependencies]
camino = "1.1.9"
clap = { version = "4.5.31", features = ["derive"] }
derive_more = { version = "2.0.1", features = ["error", "display", "from"] }
env_logger = "0.11.6"
human-sort = "0.2.2"
log = "0.4.26"
regex = "1.11.1"
zip = "2.2.3"
